/**
 * KK WebAPI
 * KK Web API for Consumer and Mobile devices 
 *
 * OpenAPI spec version: v6
 * Contact: Eslam.Nader@Hub-Apps.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

//export type PhotoTypeEnum = 1 | 2 | 3;

export enum PhotoTypeEnum {
    Thumbnail = 1,
    MainPhoto = 2,
    BackGround = 3
};